version: "3"
services:

    redis:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - frontend

    db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
                constraints: [node.role == manager]
    client:
        image: boathouse_client:latest
        ports:
            - 5000:80
        networks:
            - frontend
        depends_on:
            - redis

    result:
        image: result:latest
        ports:
            - 5001:80
        networks:
            - backend
        depends_on:
            - db

    worker:
        image: worker:latest
        networks:
            - frontend
            - backend


networks:
    frontend:
    backend:

volumes:
    db-data:
