version: "3"
services:

    client:
        image: boathouse_client:latest
        ports:
            - 5000:8080
        networks:
            - frontend
        depends_on:
            - statistics_service_redis

    management:
        image: boathouse_management:latest
        ports:
            - 5001:80
        networks:
            - backend
        depends_on:
            - statistics_service_db

    statistics_service_api:
        image: boathouse_statistics_service_api:latest
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics_service_worker:
        image: boathouse_statistics_service_worker:latest
        networks:
            - frontend
            - backend

    statistics_service_redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics_service_db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
                constraints: [node.role == manager]
networks:
    frontend:
    backend:

volumes:
    db-data:
