version: "3"
services:

    client:
        build: ./client/web
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        build: ./management/web
        ports:
            - 5001:4000
        networks:
            - backend
        depends_on:
            - statistics_service_db

    statistics_service_api:
        build: ./statistics-service/api
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics_service_worker:
        build: ./statistics-service/worker
        networks:
            - frontend
            - backend

    statistics_service_redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics_service_db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend

    product_service_api:
        build: ./product-service/api
        ports:
            - 7001:8080
        networks:
            - frontend
            - backend

    product_service_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: P2ssw0rd
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data:
