version: "3"
services:

    client:
        image: boat-house_client:latest
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        image: boat-house_management:latest
        ports:
            - 5001:4000
        networks:
            - backend
        depends_on:
            - statistics_service_db

    statistics_service_api:
        image: boat-house_statistics_service_api:latest
        ports:
            - 6001:80
        networks:
            - frontend
            - backend

    statistics_service_worker:
        image: boat-house_statistics_service_worker:latest
        networks:
            - frontend
            - backend

    statistics_service_redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - frontend

    statistics_service_db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
                constraints: [node.role == manager]

    product_service_api:
        image: boat-house_product_service_api:latest
        ports:
            - 7001:8080
        networks:
            - frontend
            - backend

    product_service_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: P2ssw0rd
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:

volumes:
    db-data:
