version: '3'

services:
  product-service-api-ci:
    image: maven:3.5.2-jdk-8-alpine
    environment: 
      - SONAR_ARGS="-Dsonar.projectKey=sonar-dev-lxm -Dsonar.host.url=http://tools.devopshub.cn:9000 -Dsonar.login=11176db2231cb44575136952d8fea2fbd603f4a4 -Dsonar.sources=src/main -Dsonar.tests=src/test
    volumes:
      - .:/build
    working_dir: /build
    command: bash -c "mvn package && mvn sonar:sonar ${SONAR_ARGS} && mvn cobertura:cobertura"

