apiVersion: v1
kind: Service
metadata:
  name: product-service-api
  namespace: boathouse-prod
spec:
  type: LoadBalancer
  ports:
  - port: 7001
    targetPort: 8080
  selector:
    app: product-service-api