name: Deploy client on dev
on: pull_request
env:
  SERVER: dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: list env
        run: env && ls 

      - name: replace project name
        run: sed -i "s|docker.pkg.github.com\/idcf-boat-house\/boat-house|docker.pkg.github.com\/${GITHUB_REPOSITORY}\/boat-house|g" kompose/test/client-*.yaml

      - name: replace docker images tags
        run: sed -i "s|:latest$|:ci|g" kompose/test/client-*.yaml

      - name: grep images url
        run: grep -i "image:" kompose/test/client-*.yaml
        #run: ls kompose/test/client-*.yaml

      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.pkg.github.com
          container-registry-username: ${GITHUB_REPOSITORY%/*}
          container-registry-password: ${{ secrets.packages_token }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'boathouse-test'
          manifests: |
             kompose/test/client-deployment.yaml
             kompose/test/client-svc.yaml
          kubectl-version: 'latest'
