name: Build client 
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build client
        run: docker build -f client/web/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/client:ci client/web

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push client tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push client tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/client:ci

name: Deploy-dev client
on: push
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: contoso.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            demo.azurecr.io/k8sdemo:${{ github.sha }}
          imagepullsecrets: |
            demo-k8s-secret
