name: Deploy client on dev
on: push
env:
  SERVER: dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.pkg.github.com
          container-registry-username: ${GITHUB_REPOSITORY%/*}
          container-registry-password: ${{ secrets.packages_token }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            demo.azurecr.io/k8sdemo:${{ github.sha }}
          imagepullsecrets: |
            demo-k8s-secret


